name: ESP32 Firmware Compilation Check

on:
  push:
    branches: [ "main" ]
    paths:
      - 'edge_runtime/**' 

jobs:
  compile-iot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installing PlatformIO Core
        run: pip install -U platformio

      - name: Compile ESP32 Code
        run: |
          cd edge_runtime
          # Perintah ini akan mencoba men-compile kode C++ untuk board ESP32
          pio ci --board esp32dev